USE [master]
GO

/****** Object:  Database [Supermercado_UNICAES]    Script Date: 6/11/2021 8:19:23 PM ******/
CREATE DATABASE [Supermercado_UNICAES]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Supermercado_UNICAES', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Supermercado_UNICAES.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Supermercado_UNICAES_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Supermercado_UNICAES_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Supermercado_UNICAES] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Supermercado_UNICAES].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Supermercado_UNICAES] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Supermercado_UNICAES] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Supermercado_UNICAES] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Supermercado_UNICAES] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Supermercado_UNICAES] SET ARITHABORT OFF 
GO

ALTER DATABASE [Supermercado_UNICAES] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Supermercado_UNICAES] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Supermercado_UNICAES] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Supermercado_UNICAES] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Supermercado_UNICAES] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Supermercado_UNICAES] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Supermercado_UNICAES] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Supermercado_UNICAES] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Supermercado_UNICAES] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Supermercado_UNICAES] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Supermercado_UNICAES] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Supermercado_UNICAES] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Supermercado_UNICAES] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Supermercado_UNICAES] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Supermercado_UNICAES] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Supermercado_UNICAES] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Supermercado_UNICAES] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Supermercado_UNICAES] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Supermercado_UNICAES] SET  MULTI_USER 
GO

ALTER DATABASE [Supermercado_UNICAES] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Supermercado_UNICAES] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Supermercado_UNICAES] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Supermercado_UNICAES] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Supermercado_UNICAES] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Supermercado_UNICAES] SET  READ_WRITE 
GO

